### ISSUE TITLE
[serial] Add Error Handling For Typical Cases

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#61]
## Situation

As described in [a comment](https://github.com/DFE/MONK/issues/53#issuecomment-18793721) to the research Issue #53 the following possible error sources in serial connections where found.
### Typical Problems
- [ ] sync time in the beginning (probably needs active I/O)
- [ ] one side might lose characters on the way
- [ ] one side might misinterprete characters
- [ ] one side might have different baudrates
- [ ] one side might have differently working clocks (which leads to misinterpretation of baudrates)
- [ ] one side might stop sending because it waits for a control signal (hardware or software flowcontrol activated on one side only, or control characters lost)
- [ ] one side might drop received data because it waits for a control signal (hardware or software flowcontrol activated on one side only, or control characters lost)
- [ ] if the connection is lost for some time mid-sending it's quite hard to find the beginning of the next character (might be solvable by small periods of at-least-one-frame-long waits)
- [ ] cable length might lead to timing errors
- [ ] [`cmd()` output might have breaks, that are much longer than reasonable timeouts](https://github.com/DFE/MONK/issues/60#issuecomment-20678121)
- [ ] [the `cmd()` call might spend more time idling or polling the connection than necessary, because he already has all output he needs](https://github.com/DFE/MONK/issues/60#issuecomment-20678121)
- [ ] [kernel output might turn an otherwise useful `cmd()` call into garbage, which might be handled with a kmod system call on the target device](https://github.com/DFE/MONK/issues/60#issuecomment-20678121)
## Solution

The `SerialConn` must respond to each of those problem sources, probably at least in one of the following ways:
- recognize when such an error happens
- inform the user about this problem (Logging and/or Exceptions)
- react with a default handling
- enable configuration and modification of the error handling
## Notes
- this Issue requires #60 to be closed first.
- branch `f-serial-errors`
- because there are a lot of different points, it is likely that this Issue will be solved in steps with other Issues
