### ISSUE TITLE
[serial] Review/Add Convenience Functions

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#62]
## Situation

There are already some convenience functions that are used quite heavily:
- `login()`
- `read_until()`

Those might be approved upon with our current foundation of experience. Also other functions like those might be added, e.g. for receiving basic status information.
## Task
- [ ] Review existing convenience functions
- [ ] Rewrite existing convenience functions for stability if necessary
- [ ] Add new ones if meaningful
## Notes
- #61 is a prerequisite to this task, although some steps might interact with this Issue
-  branch `f-serial-convenience`
