### ISSUE TITLE
[serial] Review/Resolve Known Bugs

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#63]
## Situation

There are still some bugs open about the serial connection, which might or might not be resolved automatically with solving #61. 
## Tasks
- [ ] bug tagged Issues of this milestone need to be reviewed
- [ ] unit tests need to be written that prove their current state
- [ ] Unresolved Issues need to be fixed
## Notes
- #61 is a prerequisite to this Issue
- branch maybe not necessary. Instead list bug Issues here and close them
