### ISSUE TITLE
Add Artifacts Module

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#64]
## Situation

@DfePeterWinkler wrote some classes about retrieving test artifacts like logs from a target device. Those are in use in his test suite. On the last Stammtisch it was decided to move those classes into MONK, because they can be valuable in general, not just in his test suite.
## Task
- [ ] copy the classes here
- [ ] discuss what needs to be rewritten or modified
- [ ] check [coding styleguide](https://monk_tf.readthedocs.org/en/latest/codingstyle.html)
- [ ] write unit tests
## Notes
- branch `f-add-artifacts`
