### ISSUE TITLE
Prepare release 0.1.3

### ISSUE THREAD

**Issue by erikbgithub** [DFE/MONK#78]
## Situation

Release 0.1.3 will include the final reimplementation of the whole MONK framework, as designed in my master thesis.
## Task

To solve this Issue, the following things need to be done:
- [x] check all TODO's and Issues for 0.1.2 if they are completed
- [x] complete all open issues
- [x] create and tag a release candidate
- [x] make sure all version strings are up to date
- [x] update CHANGES.txt files
- [x] update the requirements-*.txt files
- [x] present the RC at a Stammtisch to recieve the ACK to proceed
- [x] merge the accepted release candidate to the `master` branch
- [x] check and update `gh-pages` and Travis
- [x] push newest version to PyPI
## Notes
- branch `v-0.1.3-rc`
